/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.validamais.interfaces;

/**
 *
 * @author Rayanne
 */
public class TelaCadastrarAlimento extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastrarAlimento
     */
    public TelaCadastrarAlimento() {
        initComponents();
        setSize(800,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabelDigiteNome = new javax.swing.JLabel();
        jTextFieldDigiteNome = new javax.swing.JTextField();
        jLabelValidadeNome = new javax.swing.JLabel();
        jTextFieldValidadeNome = new javax.swing.JTextField();
        jComboBoxTiposMateriais = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setClosable(true);
        setMaximizable(true);
        getContentPane().setLayout(null);

        jLabelDigiteNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDigiteNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDigiteNome.setText("Digite o nome do produto");
        getContentPane().add(jLabelDigiteNome);
        jLabelDigiteNome.setBounds(70, 50, 210, 20);

        jTextFieldDigiteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDigiteNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDigiteNome);
        jTextFieldDigiteNome.setBounds(70, 80, 180, 40);

        jLabelValidadeNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelValidadeNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValidadeNome.setText("Digite a validade do produto");
        getContentPane().add(jLabelValidadeNome);
        jLabelValidadeNome.setBounds(70, 130, 270, 20);

        jTextFieldValidadeNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValidadeNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldValidadeNome);
        jTextFieldValidadeNome.setBounds(70, 170, 180, 40);

        jComboBoxTiposMateriais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alimentos(pacotes)", "Limpeza", "Frios", "Frutas" }));
        getContentPane().add(jComboBoxTiposMateriais);
        jComboBoxTiposMateriais.setBounds(70, 250, 180, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Classificação de tipo de material");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 220, 270, 22);

        jButton1.setText("SALVAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 330, 110, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/validamais/imagens/TelaPrincipal.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 800, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDigiteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDigiteNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDigiteNomeActionPerformed

    private void jTextFieldValidadeNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValidadeNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValidadeNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxTiposMateriais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDigiteNome;
    private javax.swing.JLabel jLabelValidadeNome;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldDigiteNome;
    private javax.swing.JTextField jTextFieldValidadeNome;
    // End of variables declaration//GEN-END:variables
}
